name: pleiades-hdbscan
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.26
  - pandas>=2.1
  - scikit-learn>=1.4
  - hdbscan>=0.8.36
  - matplotlib>=3.8
  - pyyaml>=6.0
  - joblib>=1.3
  - ipykernel>=6.29
  - jupyterlab>=4.0
  - pytest>=8.0
